
import {
  LayoutDashboard,
  Package,
  ShoppingCart,
  CreditCard,
  Users,
  Settings,
  BarChart3,
  Tags,
  Plus,
  List,
  Activity,
  FileText,
  RefreshCw,
  TrendingUp,
  History,
  DollarSign,
  FileBarChart,
  Calendar,
  Monitor,
  User,
} from "lucide-react";

export const menuData = [
  {
    id: "dashboard",
    title: "Dashboard",
    icon: LayoutDashboard,
    path: "/",
    iconColor: "text-cyan-400",
  },
  {
    id: "product-management",
    title: "Product Management",
    icon: Package,
    iconColor: "text-orange-400",
    children: [
      {
        id: "product-activity",
        title: "Product Activity",
        icon: Activity,
        path: "/products",
        iconColor: "text-green-400",
      },
      {
        id: "add-new-product",
        title: "Add New Product",
        icon: Plus,
        action: "add-product",
        iconColor: "text-blue-400",
      },
      {
        id: "category-management",
        title: "Category Management",
        icon: Tags,
        path: "/product/category",
        iconColor: "text-purple-400",
      },
    ],
  },
  {
    id: "sales-management",
    title: "Sales Management",
    icon: ShoppingCart,
    iconColor: "text-yellow-400",
    children: [
      {
        id: "sales-activity",
        title: "Sales Activity",
        icon: Activity,
        path: "/sales",
        iconColor: "text-green-400",
      },
      {
        id: "new-sales-entry",
        title: "New Sales Entry",
        icon: Plus,
        path: "/sales/new",
        iconColor: "text-blue-400",
      },
      {
        id: "invoice-generate",
        title: "Invoice Generate",
        icon: FileText,
        path: "/sales/invoice",
        iconColor: "text-indigo-400",
      },
    ],
  },
  {
    id: "purchase-management",
    title: "Purchase Management",
    icon: CreditCard,
    iconColor: "text-pink-400",
    children: [
      {
        id: "purchase-activity",
        title: "Purchase Activity",
        icon: Activity,
        path: "/purchase",
        iconColor: "text-green-400",
      },
      {
        id: "new-purchase-entry",
        title: "New Purchase Entry",
        icon: Plus,
        path: "/purchase/new",
        iconColor: "text-blue-400",
      },
      {
        id: "purchase-invoice",
        title: "Purchase Invoice",
        icon: FileText,
        path: "/purchase/invoice",
        iconColor: "text-indigo-400",
      },
      {
        id: "reorder-product-list",
        title: "Reorder Product List",
        icon: RefreshCw,
        path: "/purchase/reorder",
        iconColor: "text-amber-400",
      },
    ],
  },
  {
    id: "inventory-management",
    title: "Inventory Management",
    icon: Package,
    iconColor: "text-teal-400",
    children: [
      {
        id: "inventory-activity",
        title: "Inventory Activity",
        icon: Activity,
        path: "/inventory",
        iconColor: "text-green-400",
      },
      {
        id: "update-stock",
        title: "Update Stock",
        icon: TrendingUp,
        path: "/inventory/update",
        iconColor: "text-emerald-400",
      },
      {
        id: "inventory-movement-history",
        title: "Inventory Movement History",
        icon: History,
        path: "/inventory/history",
        iconColor: "text-slate-400",
      },
    ],
  },
  {
    id: "customer-management",
    title: "Customer Management",
    icon: Users,
    iconColor: "text-violet-400",
    children: [
      {
        id: "customer-information",
        title: "Customer Information",
        icon: User,
        path: "/customers",
        iconColor: "text-blue-400",
      },
      {
        id: "add-new-customer",
        title: "Add New Customer",
        icon: Plus,
        path: "/customers/new",
        iconColor: "text-green-400",
      },
      {
        id: "customer-history",
        title: "Customer History",
        icon: History,
        path: "/customers/history",
        iconColor: "text-slate-400",
      },
    ],
  },
  {
    id: "reports",
    title: "Reports & Analytics",
    icon: BarChart3,
    iconColor: "text-red-400",
    children: [
      {
        id: "sales-report",
        title: "Sales Report",
        icon: BarChart3,
        path: "/reports/sales",
        iconColor: "text-blue-400",
      },
      {
        id: "inventory-report",
        title: "Inventory Report",
        icon: Package,
        path: "/reports/inventory",
        iconColor: "text-orange-400",
      },
      {
        id: "profit-loss-report",
        title: "Profit/Loss Report",
        icon: DollarSign,
        path: "/reports/profit-loss",
        iconColor: "text-green-400",
      },
      {
        id: "periodic-reports",
        title: "Periodic Reports",
        icon: Calendar,
        path: "/reports/periodic",
        iconColor: "text-purple-400",
      },
    ],
  },
  {
    id: "expense-management",
    title: "Expense Management",
    icon: CreditCard,
    iconColor: "text-rose-400",
    children: [
      {
        id: "expense-activity",
        title: "Expense Activity",
        icon: Activity,
        path: "/expenses",
        iconColor: "text-green-400",
      },
      {
        id: "add-new-expense",
        title: "Add New Expense",
        icon: Plus,
        path: "/expenses/new",
        iconColor: "text-blue-400",
      },
      {
        id: "expense-report",
        title: "Expense Report",
        icon: FileBarChart,
        path: "/expenses/report",
        iconColor: "text-indigo-400",
      },
    ],
  },
  {
    id: "settings",
    title: "Settings",
    icon: Settings,
    iconColor: "text-gray-400",
    children: [
      {
        id: "application-settings",
        title: "Application Settings",
        icon: Settings,
        path: "/settings/app",
        iconColor: "text-gray-400",
      },
      {
        id: "user-interface",
        title: "User Interface",
        icon: Monitor,
        path: "/settings/ui",
        iconColor: "text-blue-400",
      },
    ],
  },
];
