// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lalhgdbhtrsstasqjexz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhbGhnZGJodHJzc3Rhc3FqZXh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDAzNjIsImV4cCI6MjA2NTExNjM2Mn0.vwSgtgpBUDUcESyfOPLDFTB6wwl0-foCRo1qHUNtAJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const fetchWithRetry = async (url: string, options?: RequestInit, retries = 10): Promise<Response> => {
  let lastError: Error | null = null;

  for (let i = 0; i < retries; i++) {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 45000); // 45s timeout

    try {
      const response = await fetch(url, {
        ...options,
        signal: controller.signal
      });
      clearTimeout(timeoutId);
      return response;
    } catch (error: any) {
      clearTimeout(timeoutId);
      lastError = error;

      // Log only on the final failure or if it's not a standard network error
      const isNetworkError =
        error?.name === 'TypeError' ||
        error?.message?.includes('Failed to fetch') ||
        error?.name === 'AbortError' ||
        error?.message?.includes('NetworkError') ||
        error?.message?.includes('Load failed');

      if (!isNetworkError || i === retries - 1) {
        if (i === retries - 1) {
          console.error(`Final retry attempt failed for ${url}:`, error);
        }
        break;
      }

      console.warn(`Transient network error at ${url}. Retrying (${i + 1}/${retries})...`, error.message);

      // Wait before retrying (exponential backoff with jitter)
      if (!navigator.onLine) {
        // Wait for online status or a fixed delay if offline
        await new Promise(resolve => {
          const checkOnline = () => {
            if (navigator.onLine) {
              window.removeEventListener('online', checkOnline);
              resolve(null);
            }
          };
          window.addEventListener('online', checkOnline);
          setTimeout(() => {
            window.removeEventListener('online', checkOnline);
            resolve(null);
          }, 10000); // Max wait for online 10s
        });
      }

      const delay = Math.min(Math.pow(2, i) * 1000 + Math.random() * 2000, 30000);
      await new Promise(resolve => setTimeout(resolve, delay));
    }
  }

  throw lastError || new Error('All retry attempts failed');
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: fetchWithRetry,
  }
});
