// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lalhgdbhtrsstasqjexz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhbGhnZGJodHJzc3Rhc3FqZXh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDAzNjIsImV4cCI6MjA2NTExNjM2Mn0.vwSgtgpBUDUcESyfOPLDFTB6wwl0-foCRo1qHUNtAJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const fetchWithRetry = async (url: string, options?: RequestInit, retries = 3): Promise<Response> => {
  let lastError: Error | null = null;

  for (let i = 0; i < retries; i++) {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 15000);

    try {
      const response = await fetch(url, {
        ...options,
        signal: controller.signal
      });
      clearTimeout(timeoutId);
      return response;
    } catch (error) {
      clearTimeout(timeoutId);
      lastError = error as Error;

      // Only retry on network errors or timeouts
      const isRetryable = error instanceof TypeError || (error instanceof Error && error.name === 'AbortError');
      if (!isRetryable || i === retries - 1) {
        break;
      }

      // Wait before retrying (exponential backoff)
      await new Promise(resolve => setTimeout(resolve, Math.pow(2, i) * 1000));
    }
  }

  // If all retries failed, throw the last error
  throw lastError || new Error('All retry attempts failed');
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: false, // Disable auto refresh to prevent aggressive retry loops
  },
  global: {
    fetch: fetchWithRetry,
  }
});
